#!/usr/bin/env node
/**
 * build_standalone.mjs  — V59 offline build
 * Produces a single HTML with zero external CDN dependencies:
 *   - React 18 + ReactDOM 18 UMD inlined
 *   - JSX pre-compiled by @babel/core
 *   - Tailwind CSS pre-generated by tailwindcss CLI
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import { createRequire } from 'module';
import path from 'path';
import { fileURLToPath } from 'url';
import { mkdirSync } from 'fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

const SRC  = path.join(__dirname, '_build_cache', 'GEN_v59_fixed.txt');
const OUT  = path.join(__dirname, 'dashboard', 'templates', 'strips.html');
const CACHE = path.join(__dirname, '_build_cache');

mkdirSync(CACHE, { recursive: true });

// ── Step 1: Read pre-downloaded React UMD ────────────────────────────────────
console.log('\n[1] Loading React 18 UMD...');
const reactPath    = path.join(CACHE, 'react.production.min.js');
const reactDomPath = path.join(CACHE, 'react-dom.production.min.js');

if (!existsSync(reactPath) || !existsSync(reactDomPath)) {
  console.error('ERROR: React UMD files not found in _build_cache/');
  console.error('Run this first:');
  console.error('  Invoke-WebRequest -Uri "https://unpkg.com/react@18.3.1/umd/react.production.min.js" -OutFile "_build_cache/react.production.min.js"');
  console.error('  Invoke-WebRequest -Uri "https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js" -OutFile "_build_cache/react-dom.production.min.js"');
  process.exit(1);
}

const reactJS    = readFileSync(reactPath, 'utf-8');
const reactDomJS = readFileSync(reactDomPath, 'utf-8');
console.log(`  react: ${(reactJS.length/1024).toFixed(1)} KB`);
console.log(`  react-dom: ${(reactDomJS.length/1024).toFixed(1)} KB`);

// ── Step 2: Read & prepare JSX source ────────────────────────────────────────
console.log('\n[2] Reading GEN_v59.txt...');
let jsxCode = readFileSync(SRC, 'utf-8');
jsxCode = jsxCode.replace(/^\uFEFF/, ''); // strip BOM
jsxCode = jsxCode.replace(/^\s*import\s+React[^\n]+\n?/m, '');
jsxCode = jsxCode.replace(/^\s*export\s+default\s+App;\s*$/m, '');
console.log(`  ${(jsxCode.length/1024).toFixed(0)} KB, ${jsxCode.split('\n').length} lines`);


// ── Step 2b: Targeted syntax fixes from GEN_v59.txt ──────────────────────────
console.log('\n[2b] Fixing known source syntax issues...');
// Fix #1: line 779 — id:100 object missing trailing comma before id:116
const bad1 = `{ id: 100, short: 'Gallium, Alabaster, Gold', val: 'First Base: liquid Gallium silver, Second Base: Alabaster, Third Base: Brushed Gold', hex: ['#8A8D8F', '#F2F0E6', '#D4AF37'] }`;
const fix1 = `{ id: 100, short: 'Gallium, Alabaster, Gold', val: 'First Base: liquid Gallium silver, Second Base: Alabaster, Third Base: Brushed Gold', hex: ['#8A8D8F', '#F2F0E6', '#D4AF37'] },`;
if (jsxCode.includes(bad1)) {
  jsxCode = jsxCode.replace(bad1, fix1);
  console.log('  Fixed: id:100 missing trailing comma');
} else {
  console.log('  Warn: id:100 pattern not found (may already be fixed)');
}

// Fix #2: copyToClipboard — HTTP-safe clipboard fallback
{
  const badCopy = "const copyToClipboard = () => {\n    navigator.clipboard.writeText(generatePrompt());";
  const fixCopy = `const fallbackCopy = (text) => {
    const ta = document.createElement('textarea');
    ta.value = text; ta.style.cssText = 'position:fixed;left:-9999px;top:-9999px;opacity:0';
    document.body.appendChild(ta); ta.focus(); ta.select();
    try { document.execCommand('copy'); } catch(e) {}
    document.body.removeChild(ta);
  };
  const copyToClipboard = () => {
    const text = generatePrompt();
    if (navigator.clipboard && window.isSecureContext) {
      navigator.clipboard.writeText(text).catch(() => fallbackCopy(text));
    } else { fallbackCopy(text); }`;
  if (jsxCode.includes(badCopy)) {
    jsxCode = jsxCode.replace(badCopy, fixCopy);
    console.log('  Fixed: copyToClipboard — HTTP clipboard fallback added');
  } else {
    console.log('  Warn: copyToClipboard pattern not found, trying alternate...');
    // Try to patch just the navigator.clipboard call
    jsxCode = jsxCode.replace(
      /navigator\.clipboard\.writeText\(generatePrompt\(\)\)/,
      `(function(){const text=generatePrompt();if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(text)}else{const ta=document.createElement('textarea');ta.value=text;ta.style.cssText='position:fixed;left:-9999px;top:-9999px';document.body.appendChild(ta);ta.focus();ta.select();try{document.execCommand('copy')}catch(e){}document.body.removeChild(ta)}})()`
    );
    console.log('  Applied alternate clipboard patch');
  }
}

// Fix #3: getSelectedText — null guard for Array.find returning undefined
jsxCode = jsxCode.replace(
  /const item = searchItems\.find\(i => i\.id === id\);\s*\n\s*if \(!item\) return '';/,
  `const item = searchItems ? searchItems.find(i => i.id === id) : undefined;\n        if (!item) return '';`
);

// ── Step 3: Compile JSX → vanilla JS ─────────────────────────────────────────
console.log('\n[3] Compiling JSX with @babel/core...');
const babel = require('@babel/core');
const result = babel.transformSync(jsxCode, {
  presets: [['@babel/preset-react', { runtime: 'classic' }]],
  filename: 'strips.jsx',
  sourceMaps: false,
  compact: false,
});
const compiledJS = result.code;
console.log(`  Compiled: ${(compiledJS.length/1024).toFixed(0)} KB`);

// ── Step 4: Generate Tailwind CSS ────────────────────────────────────────────
console.log('\n[4] Generating Tailwind CSS (scanning JSX)...');
const tmpJsx = path.join(CACHE, 'tmp_source.jsx');
writeFileSync(tmpJsx, jsxCode, 'utf-8');

writeFileSync(path.join(CACHE, 'tailwind.config.js'), `
module.exports = {
  content: [${JSON.stringify(tmpJsx)}],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Menlo', 'monospace'],
        serif: ['Georgia', 'serif'],
      }
    }
  },
  plugins: [],
}
`);

writeFileSync(path.join(CACHE, 'input.css'),
  '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n');

const cssOut = path.join(CACHE, 'output.css');
const twBin  = path.join(__dirname, 'node_modules', '.bin', 'tailwindcss');

execSync(
  `"${twBin}" -c "${path.join(CACHE,'tailwind.config.js')}" -i "${path.join(CACHE,'input.css')}" -o "${cssOut}" --minify`,
  { cwd: __dirname, stdio: 'inherit', timeout: 180000 }
);
const twCSS = readFileSync(cssOut, 'utf-8');
console.log(`  Tailwind CSS: ${(twCSS.length/1024).toFixed(0)} KB`);

// ── Step 5: Assemble final HTML ───────────────────────────────────────────────
console.log('\n[5] Assembling final HTML...');

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>STRIPS PRO GEN — V59: FULL RESTORATION</title>
  <meta name="description" content="K.S.A.R. / P.S.D.N. Prompt Generator. V59 Full Restoration." />
  <!-- Fonts: optional, degrades gracefully if offline -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet" />
  <style>
${twCSS}
    *{box-sizing:border-box}
    body{margin:0;padding:0;background:#050608}
    .custom-scrollbar::-webkit-scrollbar{width:6px}
    .custom-scrollbar::-webkit-scrollbar-track{background:#050608}
    .custom-scrollbar::-webkit-scrollbar-thumb{background:#23262e;border-radius:4px}
    .custom-scrollbar::-webkit-scrollbar-thumb:hover{background:#c8aa6e}
    @media print{@page{margin:0;size:A4}body{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important;background:white}}
  </style>
</head>
<body>
  <div id="root"></div>
  <script>
/* React 18 UMD — inlined */
${reactJS}
  </script>
  <script>
/* ReactDOM 18 UMD — inlined */
${reactDomJS}
  </script>
  <script>
/* Strips Pro Gen V59 — pre-compiled from GEN_v59.txt */
/* React hooks — destructured from global React UMD */
var useState=React.useState,useEffect=React.useEffect,useMemo=React.useMemo,useCallback=React.useCallback,useRef=React.useRef,useReducer=React.useReducer,useContext=React.useContext,createContext=React.createContext;
${compiledJS}


/* Mount */
(function(){
  var rootEl = document.getElementById('root');
  ReactDOM.createRoot(rootEl).render(React.createElement(App, null));
})();
  </script>
</body>
</html>`;

writeFileSync(OUT, html, 'utf-8');
const sizeKB = (readFileSync(OUT).length / 1024).toFixed(0);
console.log(`\n✅ SUCCESS: strips.html — ${sizeKB} KB`);
console.log(`   Output: ${OUT}`);
console.log('   Zero external dependencies. Works fully offline.\n');
